"""descripcion del cambio

Revision ID: a3fea3ac7a97
Revises: cd77ae671185
Create Date: 2026-01-19 02:43:12.134661

"""
from __future__ import annotations

from alembic import op #type: ignore
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3fea3ac7a97'
down_revision = 'cd77ae671185'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###