"""descripcion del cambio

Revision ID: bf8f809cb00e
Revises: 1c2c42f8e1b5
Create Date: 2026-01-19 22:22:49.796989

"""
from __future__ import annotations

from alembic import op #type: ignore
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8f809cb00e'
down_revision = '1c2c42f8e1b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###