// src/context/LanguageContext.jsx
import { createContext, useContext, useEffect, useMemo, useState } from "react";

const LanguageContext = createContext();

const TRANSLATIONS = {
  es: {
    nav: {
      home: "Home",
      store: "Tienda",
      offers: "Ofertas",
      faq: "FAQ",
      contact: "Contáctanos",
      admin: "Admin",
      cart: "Carrito",
      login: "Iniciar sesión",
      signup: "Crear cuenta",
      account: "Mi cuenta",
      adminPanel: "Panel admin",
      profile: "Mi perfil",
      logout: "Cerrar sesión",
      changeLanguage: "Cambiar idioma",
      goToCart: "Ir al carrito",
      myOrders: "Mis pedidos",
      theme: "Tema",
      toggleTheme: "Cambiar tema",
    },
    home: {
      title: "Bienvenido a Abul Cell",
      subtitle: "Tu tienda de productos electrónicos",
      heroChip: "Compra segura • Soporte real",
      heroSubtitle:
        "Tu tienda de confianza para celulares, notebooks y periféricos gamers. Comprá fácil, rápido y seguro.",
      viewStore: "Ver tienda",
      viewDeals: "Ver ofertas",
      benefits: {
        shipping: "Envíos a todo el país",
        payment: "Pagos seguros con Mercado Pago",
        support: "Atención personalizada",
      },
      devicePills: {
        phones: "Celulares",
        laptops: "Notebooks",
        gaming: "Gaming",
      },
      categories: {
        title: "Categorías principales",
        subtitle: "Todo lo que necesitás para tu setup y tu día a día.",
        viewAll: "Ver todo",
        items: {
          phones: {
            title: "Celulares",
            description: "Gama alta, media y opciones económicas.",
          },
          laptops: {
            title: "Notebooks",
            description: "Equipos para estudio, trabajo y gaming.",
          },
          peripherals: {
            title: "Periféricos",
            description: "Teclados, mouse, pads y más.",
          },
          audio: {
            title: "Audio",
            description: "Auriculares, parlantes y soundbars.",
          },
          gaming: {
            title: "Gaming",
            description: "Monitores, sillas gamers y accesorios.",
          },
          accessories: {
            title: "Accesorios",
            description: "Fundas, cargadores, cables y mucho más.",
          },
        },
      },
      highlight: {
        title: "¿Por qué comprar en Abul Cell?",
        items: {
          curated: {
            title: "Productos seleccionados",
            description: "Solo marcas confiables y modelos probados, nada de humo.",
          },
          advice: {
            title: "Asesoramiento real",
            description: "Te ayudamos a elegir el equipo ideal para tu uso y presupuesto.",
          },
          payments: {
            title: "Pagos flexibles",
            description: "Mercado Pago, cuotas y distintos métodos para que sea más fácil.",
          },
        },
      },
    },
    cart: {
      title: "Tu carrito",
      empty: "Tu carrito está vacío.",
      goToStore: "Ir a la tienda",
      productAdded_one: "producto agregado",
      productAdded_other: "productos agregados",
      clear: "Vaciar carrito",
      summary: "Resumen",
      totalProducts: "Total productos",
      total: "Total",
      goToCheckout: "Ir al checkout",
      remove: "Quitar",
      quantity: "Cantidad",
      toastRemoved: "Producto eliminado del carrito",
      toastRemovedOne: "Quitado 1",
      toastAddedOne: "Agregado 1",
      decrease: "Restar",
      increase: "Sumar",
      maxStock: "Stock máximo alcanzado",
      subtotal: "Subtotal",
      tip: "Tip: revisá tu pedido antes de pagar ✨",
    },
    cartMini: {
      items_one: "{count} ítem",
      items_other: "{count} ítems",
      emptyTitle: "Carrito vacío",
      emptySubtitle: "Agregá productos y aparecen acá.",
      goToStore: "Ir a la tienda",
      removeItem: "Quitar {name}",
      moreItems: "+{count} más…",
      viewCart: "Ver carrito",
    },
    checkout: {
      title: "Checkout",
      name: "Nombre completo",
      email: "Correo electrónico",
      phone: "Teléfono (opcional)",
      city: "Ciudad",
      province: "Provincia",
      postalCode: "Código postal",
      notes: "Notas (opcional)",
      paymentMethod: "Método de pago",
      payment_card: "Tarjeta",
      payment_cash: "Efectivo en el local",
      payment_transfer: "Transferencia bancaria",
      submit: "Confirmar compra",
      empty: "Tu carrito está vacío.",
      backToStore: "Volver a la tienda",
      backToCart: "Volver al carrito",
      secureBadge: "Compra segura",
      subtitle: "Completá tus datos y elegí el método de pago.",
      billingTitle: "Datos de facturación y envío",
      deliveryTitle: "Entrega",
      paymentTitle: "Medios de pago",
      summaryTitle: "Resumen de compra",
      missingFieldsLabel: "Campos obligatorios faltantes:",
      processing: "Procesando...",
      fields: {
        name: "Nombre y apellido",
        email: "Correo electrónico",
        phone: "Teléfono",
        notes: "Notas",
        nameRequired: "Nombre y apellido *",
        emailRequired: "Email *",
        notesOptional: "Notas (opcional)",
      },
      delivery: {
        pickup: "Retiro en el local",
        delivery: "Envío a domicilio",
        areaNote: "Envíos disponibles solo para el exterior de Buenos Aires.",
        savedAddressHint: "Elegí una dirección guardada (o cargá una manual).",
        loading: "Cargando direcciones...",
        savedAddressLabel: "Dirección guardada",
        noSavedAddresses: "No tenés direcciones guardadas todavía.",
        manualHint: "Completá una dirección manual para continuar con el envío.",
        typeLabel: "Tipo",
        types: {
          house: "Casa",
          apartment: "Departamento",
          office: "Oficina",
          other: "Otro",
        },
        streetLabel: "Calle y número",
        streetPlaceholder: "Av. Siempre Viva 123",
        cityLabel: "Ciudad",
        cityPlaceholder: "Buenos Aires",
        provinceLabel: "Provincia",
        provincePlaceholder: "CABA / Buenos Aires",
        postalCodeLabel: "CP (opcional)",
        postalCodePlaceholder: "1406",
        apartmentLabel: "Depto (opcional)",
        apartmentPlaceholder: "2B",
        floorLabel: "Piso (opcional)",
        floorPlaceholder: "3",
        bellLabel: "Timbre (opcional)",
        bellPlaceholder: "Moreno / 3B",
        notesLabel: "Indicaciones (opcional)",
        notesPlaceholder: "Portón negro, entre calles..., etc.",
      },
      payment: {
        recommended: "Recomendado",
        mercadoPago: {
          title: "Mercado Pago",
          subtitle: "Te redirigimos a Mercado Pago para completar el pago.",
        },
        cash: {
          title: "Efectivo al retirar",
          subtitle: "Pagás en el local cuando venís a buscar tu pedido.",
          amountLabel: "¿Con cuánto abonás?",
          amountPlaceholder: "Ej: 20000",
          amountHint: "Te lo pedimos para preparar el cambio (si hace falta).",
        },
      },
      address: {
        pickupLabel: "RETIRO EN LOCAL",
        deliveryLabel: "ENVÍO",
        postalCodePrefix: "CP",
      },
      quantityLabel: "Cantidad: {count}",
      success: {
        title: "¡Gracias por tu compra!",
        orderNumber: "Registramos tu orden con el número #{orderId}.",
        emailNotice: "En breve te va a llegar un correo con el detalle de la compra.",
        backHome: "Volver al inicio",
      },
      errors: {
        emptyCartTitle: "Carrito vacío",
        emptyCartMessage: "Agregá productos antes de continuar.",
        missingFields: "Por favor completá todos los campos obligatorios.",
        missingAddress: "Completá la dirección de envío.",
        missingCashAmount: "Indicá con cuánto vas a abonar (solo números).",
        cashTooLow: "El monto con el que abonás no puede ser menor al total.",
        generic: "Ocurrió un error al procesar la compra.",
      },
    },
    auth: {
      login: {
        secureBadge: "Login seguro",
        title: "Iniciar sesión",
        emailLabel: "Email",
        emailPlaceholder: "tu@email.com",
        passwordLabel: "Contraseña",
        passwordPlaceholder: "••••••••",
        showPassword: "Mostrar contraseña",
        hidePassword: "Ocultar contraseña",
        recoverHint: "¿No podés entrar? Probá recuperar tu contraseña.",
        recoverLink: "Recuperar contraseña",
        loading: "Ingresando...",
        loadingButton: "Ingresando...",
        submit: "Ingresar",
        noAccount: "¿No tenés cuenta?",
        signupLink: "Crear cuenta",
        toastSuccessTitle: "Sesión iniciada",
        toastSuccessMessage: "Bienvenido nuevamente {email}",
        toastErrorTitle: "Error al iniciar sesión",
        toastErrorMessage: "Email o contraseña incorrectos",
      },
      signup: {
        badge: "Crear cuenta",
        title: "Crear cuenta",
        subtitle: "Registrate para seguir tus compras en Abul Cell.",
        nameLabel: "Nombre",
        namePlaceholder: "Tu nombre",
        emailLabel: "Email",
        emailPlaceholder: "tu@email.com",
        passwordLabel: "Contraseña",
        passwordPlaceholder: "Mínimo 8 caracteres",
        repeatPasswordLabel: "Repetir contraseña",
        repeatPasswordPlaceholder: "Repetí tu contraseña",
        showPassword: "Mostrar contraseña",
        hidePassword: "Ocultar contraseña",
        loading: "Creando cuenta...",
        loadingButton: "Registrando...",
        submit: "Registrarse",
        haveAccount: "¿Ya tenés una cuenta?",
        loginLink: "Iniciá sesión",
        successTitle: "Cuenta creada",
        successMessage: "Tu cuenta fue creada correctamente. Ahora podés iniciar sesión.",
        errorTitle: "Error al registrarse",
        errorMessage: "No se pudo crear la cuenta",
        passwordMismatchTitle: "Contraseñas distintas",
        passwordMismatchMessage: "Las contraseñas no coinciden",
      },
      forgotPassword: {
        title: "Recuperar contraseña",
        subtitle: "Te vamos a mandar un link para que puedas crear una contraseña nueva.",
        emailLabel: "Email",
        emailPlaceholder: "tu@email.com",
        submit: "Enviar link",
        sending: "Enviando...",
        backToLogin: "Volver al login",
        successTitle: "Listo.",
        successMessage: "Si el mail existe, te va a llegar un correo con el link de recuperación.",
        errors: {
          missingEmail: "Ingresá tu correo.",
          generic: "No se pudo procesar la solicitud.",
        },
      },
      resetPassword: {
        title: "Nueva contraseña",
        subtitle: "Ingresá tu nueva contraseña y confirmala.",
        passwordLabel: "Nueva contraseña",
        passwordPlaceholder: "Mínimo 8 caracteres",
        confirmPasswordLabel: "Repetir contraseña",
        confirmPasswordPlaceholder: "Repetí tu contraseña",
        showPassword: "Mostrar contraseña",
        hidePassword: "Ocultar contraseña",
        saving: "Guardando...",
        submit: "Cambiar contraseña",
        backToLogin: "Volver al login",
        requestLink: "Pedir link de nuevo",
        successTitle: "Contraseña actualizada.",
        successMessage: "Te redirigimos al login…",
        errors: {
          missingToken: "Token inválido o faltante. Volvé a pedir el link.",
          missingTokenInline: "Falta el token. Pedí nuevamente el link de recuperación.",
          shortPassword: "La contraseña debe tener al menos 8 caracteres.",
          passwordMismatch: "Las contraseñas no coinciden.",
          generic: "No se pudo cambiar la contraseña.",
        },
      },
      verifyEmail: {
        title: "Verificá tu email",
        subtitle: "Te enviamos un código a",
        codeLabel: "Código (6 dígitos)",
        codePlaceholder: "123456",
        confirm: "Confirmar",
        verifying: "Verificando...",
        resend: "Reenviar código",
        resendSuccess: "Listo ✅ Te enviamos un nuevo código.",
        later: "Verificar más tarde",
        hint: "Podés verificarlo más tarde desde",
        profileLink: "Mi perfil",
        errors: {
          shortCode: "Ingresá el código de 6 dígitos.",
          invalidCode: "Código inválido.",
          resendFailed: "No se pudo reenviar.",
        },
      },
    },
    profile: {
      title: "Mi perfil",
      subtitle: "Gestioná tus datos de cuenta.",
      loginRequired: "Necesitás iniciar sesión para ver tu perfil.",
      goToLogin: "Ir a login",
      theme: {
        title: "Tema",
        description: "Elegí cómo querés ver la app.",
        toggle: "Cambiar tema",
        light: "Modo claro",
        dark: "Modo oscuro",
      },
      labels: {
        name: "Nombre",
        email: "Email",
        verification: "Verificación",
      },
      verified: "Verificado",
      pending: "Pendiente",
      verify: {
        title: "Tu email todavía no está verificado.",
        subtitle: "Revisá tu casilla. Si no te llegó el código, podés reenviarlo.",
        success: "Listo ✅ Te reenviamos el código. Revisá tu mail.",
        error: "No se pudo reenviar el código.",
        loading: "Reenviando...",
        resend: "Reenviar verificación",
        enterCode: "Ingresar código ahora",
      },
      addresses: {
        title: "Mis direcciones",
        loading: "Cargando direcciones...",
        empty: "No tenés direcciones guardadas.",
        default: "Predeterminada",
        postalCode: "CP:",
        apartment: "Depto",
        floor: "Piso",
        bell: "Timbre",
        makeDefault: "Hacer predeterminada",
        edit: "Editar",
        delete: "Eliminar",
        cancelEdit: "Cancelar edición",
        types: {
          house: "Casa",
          apartment: "Depto",
          office: "Oficina",
        },
      },
      addressErrors: {
        load: "No se pudieron cargar las direcciones",
        delete: "No se pudo eliminar la dirección",
        setDefault: "No se pudo marcar como predeterminada.",
      },
      addressForm: {
        title: "Agregar dirección",
        labelPlaceholder: "Casa, Trabajo...",
        streetPlaceholder: "Calle y número",
        cityPlaceholder: "Ciudad",
        provincePlaceholder: "Provincia",
        postalCodePlaceholder: "Código postal",
        typeLabel: "Tipo",
        types: {
          house: "Casa",
          apartment: "Departamento",
          office: "Oficina",
          other: "Otro",
        },
        apartmentLabel: "Depto (opcional)",
        apartmentPlaceholder: "A, 2B, etc.",
        floorLabel: "Piso (opcional)",
        floorPlaceholder: "3",
        bellLabel: "Timbre (opcional)",
        bellPlaceholder: "Moreno / 3B",
        notesLabel: "Indicaciones (opcional)",
        notesPlaceholder: "Entre calles..., portón negro, etc.",
        setDefault: "Usar como predeterminada",
        submit: "Guardar dirección",
      },
    },
    contact: {
      badge: "Contacto",
      title: "Contáctanos",
      subtitle: "¿Tenés dudas sobre un producto o querés un presupuesto? Escribinos.",
      sending: "Enviando mensaje...",
      toastSuccessTitle: "Mensaje enviado",
      toastSuccessMessage: "¡Gracias! Te vamos a responder a la brevedad.",
      toastErrorTitle: "No se pudo enviar",
      toastErrorMessage: "Ocurrió un error al enviar tu mensaje. Probá de nuevo.",
      form: {
        nameLabel: "Nombre",
        emailLabel: "Email",
        subjectLabel: "Asunto",
        messageLabel: "Mensaje",
        attachmentsLabel: "Adjuntos (comprobante / fotos)",
        attachmentsHint: "Imágenes o PDF. Máx 8MB total.",
        sending: "Enviando...",
        submit: "Enviar mensaje",
      },
      storeDetailsTitle: "Datos del local",
      storeAddressLabel: "Dirección:",
      storeAddressValue: "(acá va la dirección real de Abul Cell)",
      storeHoursLabel: "Horario:",
      storeHoursValue: "Lunes a viernes de 10 a 19 hs.",
      storeEmailLabel: "Email:",
      storePhoneLabel: "Teléfono:",
    },
    offers: {
      badge: "Ofertas",
      title: "Ofertas",
      subtitle: "Productos con descuentos especiales en Abul Cell.",
      states: {
        loadingTitle: "Cargando ofertas…",
        loadingSubtitle: "Buscando lo mejor para vos.",
        errorTitle: "No pudimos cargar las ofertas",
        errorSubtitle: "Probá de nuevo en un instante.",
        emptyTitle: "Por ahora no hay ofertas activas",
        emptySubtitle: "Volvé más tarde, siempre hay novedades.",
      },
    },
    store: {
      badge: "Tienda",
      title: "Tienda",
      subtitle: "Explorá todos los productos de Abul Cell.",
      categories: {
        phones: "Celulares",
        laptops: "Notebooks",
        peripherals: "Periféricos",
        audio: "Audio",
        gaming: "Gaming",
        accessories: "Accesorios",
      },
      actions: {
        loading: "Cargando...",
        refresh: "Actualizar",
        clear: "Limpiar",
        retry: "Reintentar",
        clearFilters: "Limpiar filtros",
      },
      filters: {
        searchLabel: "Buscar",
        searchPlaceholder: "Buscar por nombre o descripción...",
        clearSearch: "Limpiar búsqueda",
        categoryLabel: "Categoría",
        allCategories: "Todas las categorías",
        sortLabel: "Orden",
        sort: {
          relevance: "Relevancia",
          priceAsc: "Precio: menor a mayor",
          priceDesc: "Precio: mayor a menor",
          nameAsc: "Nombre: A-Z",
        },
        resultsLabel: "Resultados",
        resultsPlaceholder: "—",
      },
      states: {
        loadingTitle: "Cargando productos…",
        loadingSubtitle: "Aguantá un toque, ya aparece el catálogo.",
        errorTitle: "Ocurrió un error al cargar los productos",
        errorSubtitle: "Probá de nuevo. Si persiste, revisamos el endpoint.",
        emptyTitle: "No encontramos productos con esos filtros",
        emptySubtitle: "Probá cambiar la categoría o limpiar la búsqueda.",
      },
    },
    productCard: {
      offer: "Oferta",
      outOfStock: "Sin stock",
      noImage: "Sin imagen",
      stock: {
        ok: "Stock: {stock}",
        low: "Últimas {stock}",
      },
      removeOne: "Quitar uno",
      maxStock: "Stock máximo alcanzado",
      addToCart: "Agregar al carrito",
      added: "Agregado",
      add: "Agregar",
    },
    admin: {
      title: "Panel de administración",
      subtitle: "Hola, {name}. Gestioná Abul Cell.",
      accessDenied: {
        title: "Acceso denegado",
        subtitle: "No tenés permisos para ver esta sección.",
        back: "Volver",
      },
      errors: {
        loadProducts: "No se pudieron cargar los productos.",
        loadOrders: "No se pudieron cargar las órdenes.",
        loadUsers: "No se pudieron cargar los usuarios.",
        saveProduct: "No se pudo guardar el producto.",
        deleteProduct: "No se pudo eliminar el producto.",
        updateOrderStatus: "No se pudo actualizar el estado.",
      },
      notifications: {
        productUpdated: "Producto actualizado.",
        productCreated: "Producto creado.",
        productDeleted: "Producto eliminado.",
        orderUpdated: "Estado de la orden actualizado.",
      },
      headerSubtitle: {
        products: "{count} productos",
        payments: "{count} órdenes",
        users: "Gestión de usuarios",
        profits: "Ingresos con órdenes pagadas",
      },
      kpis: {
        products: "{count} productos",
        catalog: "Gestión de catálogo",
        orders: "{count} órdenes",
        payments: "Pagos y estados",
        users: "{count} usuarios",
        today: "Hoy: ${amount}",
        week: "Semana: ${amount}",
        month: "Mes: ${amount}",
        year: "Año: ${amount}",
      },
      pagination: {
        showing: "Mostrando {start} – {end} de {total}",
        prev: "Anterior",
        next: "Siguiente",
      },
      payments: {
        title: "Pagos / Órdenes",
        loading: "Cargando órdenes...",
        empty: "Todavía no hay órdenes registradas.",
        headers: {
          customer: "Cliente",
          method: "Método",
          date: "Fecha",
          status: "Estado",
          total: "Total",
        },
        status: {
          pending: "Pendiente",
          paid: "Pagada",
          cancelled: "Cancelada",
        },
      },
      users: {
        title: "Usuarios",
        loading: "Cargando...",
        loadingList: "Cargando usuarios...",
        refresh: "Actualizar",
        empty: "No hay usuarios para mostrar.",
        headers: {
          id: "ID",
          name: "Nombre",
          email: "Email",
          role: "Rol",
        },
        roles: {
          admin: "Admin",
          user: "Usuario",
        },
      },
      products: {
        form: {
          editTitle: "Editar producto",
          newTitle: "Nuevo producto",
          idLabel: "ID {id}",
          editDescription: "Modificá los datos del producto y guardá los cambios.",
          newDescription: "Completá los datos para agregar un producto a la tienda.",
          name: "Nombre",
          slug: "Slug (identificador único)",
          price: "Precio (ARS)",
          stock: "Stock",
          stockPlaceholder: "0",
          category: "Categoría",
          categoryPlaceholder: "Celulares, Notebooks, Accesorios...",
          imageFile: "Imagen del producto",
          imageFileHint: "Subí una imagen desde tu computadora (JPG/PNG/WebP).",
          imageUrl: "URL de imagen (opcional)",
          imageUrlPlaceholder: "https://... (opcional)",
          description: "Descripción",
          isOffer: "Marcar como oferta",
          offerLabel: "Etiqueta de oferta",
          offerPlaceholder: "10% OFF, OFERTA, etc.",
          saving: "Guardando...",
          save: "Guardar cambios",
          create: "Crear producto",
          cancel: "Cancelar",
        },
        summary: {
          total: "Total",
          offers: "Ofertas",
          lowStock: "Stock bajo",
        },
        list: {
          title: "Productos actuales",
          loading: "Cargando productos...",
          empty: "No hay productos cargados todavía.",
          headers: {
            name: "Nombre",
            category: "Categoría",
            price: "Precio",
            stock: "Stock",
            offer: "Oferta",
            actions: "Acciones",
          },
          offer: "Oferta",
          uncategorized: "Sin categoría",
        },
      },
      profits: {
        title: "Ganancias",
        kpis: {
          today: "Hoy",
          week: "Semana",
          month: "Mes",
          year: "Año",
        },
        chartTitle: {
          week: "Últimos 7 días",
          month: "Últimos 12 meses",
          year: "Últimos 5 años",
        },
        chartSubtitle: "Ingresos por período",
        range: {
          week: "Semana",
          month: "Mes",
          year: "Año",
        },
      },
      confirm: {
        title: "Confirmar eliminación",
        subtitle: "Vas a eliminar {name}. Esta acción no se puede deshacer.",
        fallbackItem: "este producto",
        close: "Cerrar",
        cancel: "Cancelar",
        deleting: "Eliminando...",
        confirm: "Sí, eliminar",
      },
      sidebar: {
        title: "Navegación",
        products: "Productos",
        payments: "Pagos",
        users: "Usuarios",
        profits: "Ganancias",
      },
    },
    checkoutStatus: {
      success: {
        badge: "Pago acreditado",
        title: "Pago exitoso",
        subtitle: "¡Gracias por tu compra! En breve recibirás un correo con los detalles.",
        steps: {
          email: {
            title: "Confirmación por email",
            subtitle: "Te llega el detalle del pedido y el estado del pago.",
          },
          prep: {
            title: "Preparación del pedido",
            subtitle: "Armamos tu compra y coordinamos el envío/retiro.",
          },
        },
        actions: {
          home: "Volver al inicio",
          store: "Seguir comprando",
        },
      },
      failure: {
        badge: "Pago no completado",
        title: "Pago no completado",
        subtitle:
          "Tu pago no se pudo completar. No te preocupes: no se confirma la compra hasta que el pago se acredite.",
        tips: {
          balance: "Revisá que tengas saldo / límite disponible.",
          method: "Probá con otra tarjeta o método dentro de Mercado Pago.",
          retry: "Si se trabó el flujo, volvé al carrito y reintentá.",
        },
        actions: {
          retry: "Reintentar pago",
          cart: "Volver al carrito",
          store: "Ir a la tienda",
        },
      },
    },
  },
  en: {
    nav: {
      home: "Home",
      store: "Store",
      offers: "Deals",
      faq: "FAQ",
      contact: "Contact us",
      admin: "Admin",
      cart: "Cart",
      login: "Log in",
      signup: "Sign up",
      account: "My account",
      adminPanel: "Admin panel",
      profile: "My profile",
      logout: "Log out",
      changeLanguage: "Change language",
      goToCart: "Go to cart",
      myOrders: "My orders",
      theme: "Theme",
      toggleTheme: "Toggle theme",
    },
    home: {
      title: "Welcome to Abul Cell",
      subtitle: "Your electronic products store",
      heroChip: "Secure checkout • Real support",
      heroSubtitle:
        "Your trusted store for phones, laptops, and gaming accessories. Shop fast, simple, and safe.",
      viewStore: "View store",
      viewDeals: "View deals",
      benefits: {
        shipping: "Nationwide shipping",
        payment: "Secure payments with Mercado Pago",
        support: "Personalized support",
      },
      devicePills: {
        phones: "Phones",
        laptops: "Laptops",
        gaming: "Gaming",
      },
      categories: {
        title: "Top categories",
        subtitle: "Everything you need for your setup and daily life.",
        viewAll: "View all",
        items: {
          phones: {
            title: "Phones",
            description: "High-end, mid-range, and budget options.",
          },
          laptops: {
            title: "Laptops",
            description: "Gear for study, work, and gaming.",
          },
          peripherals: {
            title: "Peripherals",
            description: "Keyboards, mice, pads, and more.",
          },
          audio: {
            title: "Audio",
            description: "Headphones, speakers, and soundbars.",
          },
          gaming: {
            title: "Gaming",
            description: "Monitors, gaming chairs, and accessories.",
          },
          accessories: {
            title: "Accessories",
            description: "Cases, chargers, cables, and more.",
          },
        },
      },
      highlight: {
        title: "Why shop at Abul Cell?",
        items: {
          curated: {
            title: "Curated products",
            description: "Only trusted brands and proven models, no fluff.",
          },
          advice: {
            title: "Real advice",
            description: "We help you choose the right gear for your needs and budget.",
          },
          payments: {
            title: "Flexible payments",
            description: "Mercado Pago, installments, and more options to keep it easy.",
          },
        },
      },
    },
    cart: {
      title: "Your cart",
      empty: "Your cart is empty.",
      goToStore: "Go to store",
      productAdded_one: "product added",
      productAdded_other: "products added",
      clear: "Clear cart",
      summary: "Summary",
      totalProducts: "Total products",
      total: "Total",
      goToCheckout: "Go to checkout",
      remove: "Remove",
      quantity: "Quantity",
      toastRemoved: "Product removed from cart",
      toastRemovedOne: "Removed 1",
      toastAddedOne: "Added 1",
      decrease: "Decrease",
      increase: "Increase",
      maxStock: "Maximum stock reached",
      subtotal: "Subtotal",
      tip: "Tip: review your order before paying ✨",
    },
    cartMini: {
      items_one: "{count} item",
      items_other: "{count} items",
      emptyTitle: "Cart is empty",
      emptySubtitle: "Add products and they will appear here.",
      goToStore: "Go to store",
      removeItem: "Remove {name}",
      moreItems: "+{count} more…",
      viewCart: "View cart",
    },
    checkout: {
      title: "Checkout",
      name: "Full name",
      email: "Email",
      phone: "Phone (optional)",
      city: "City",
      province: "State / Province",
      postalCode: "ZIP / Postal code",
      notes: "Notes (optional)",
      paymentMethod: "Payment method",
      payment_card: "Card",
      payment_cash: "Cash at store",
      payment_transfer: "Bank transfer",
      submit: "Confirm order",
      empty: "Your cart is empty.",
      backToStore: "Back to store",
      backToCart: "Back to cart",
      secureBadge: "Secure checkout",
      subtitle: "Fill in your details and choose a payment method.",
      billingTitle: "Billing and shipping details",
      deliveryTitle: "Delivery",
      paymentTitle: "Payment methods",
      summaryTitle: "Order summary",
      missingFieldsLabel: "Missing required fields:",
      processing: "Processing...",
      fields: {
        name: "Full name",
        email: "Email",
        phone: "Phone",
        notes: "Notes",
        nameRequired: "Full name *",
        emailRequired: "Email *",
        notesOptional: "Notes (optional)",
      },
      delivery: {
        pickup: "In-store pickup",
        delivery: "Home delivery",
        areaNote: "Delivery available only outside Buenos Aires.",
        savedAddressHint: "Choose a saved address (or enter one manually).",
        loading: "Loading addresses...",
        savedAddressLabel: "Saved address",
        noSavedAddresses: "You don’t have saved addresses yet.",
        manualHint: "Fill in a manual address to continue with delivery.",
        typeLabel: "Type",
        types: {
          house: "House",
          apartment: "Apartment",
          office: "Office",
          other: "Other",
        },
        streetLabel: "Street and number",
        streetPlaceholder: "742 Evergreen Terrace",
        cityLabel: "City",
        cityPlaceholder: "Buenos Aires",
        provinceLabel: "State / Province",
        provincePlaceholder: "CABA / Buenos Aires",
        postalCodeLabel: "ZIP / Postal code (optional)",
        postalCodePlaceholder: "1406",
        apartmentLabel: "Apartment (optional)",
        apartmentPlaceholder: "2B",
        floorLabel: "Floor (optional)",
        floorPlaceholder: "3",
        bellLabel: "Doorbell (optional)",
        bellPlaceholder: "Moreno / 3B",
        notesLabel: "Delivery notes (optional)",
        notesPlaceholder: "Black gate, between streets..., etc.",
      },
      payment: {
        recommended: "Recommended",
        mercadoPago: {
          title: "Mercado Pago",
          subtitle: "We redirect you to Mercado Pago to complete the payment.",
        },
        cash: {
          title: "Cash on pickup",
          subtitle: "Pay at the store when you pick up your order.",
          amountLabel: "How much will you pay with?",
          amountPlaceholder: "e.g. 20000",
          amountHint: "We ask to prepare change if needed.",
        },
      },
      address: {
        pickupLabel: "IN-STORE PICKUP",
        deliveryLabel: "DELIVERY",
        postalCodePrefix: "ZIP",
      },
      quantityLabel: "Quantity: {count}",
      success: {
        title: "Thanks for your purchase!",
        orderNumber: "We recorded your order with number #{orderId}.",
        emailNotice: "You will receive an email shortly with the order details.",
        backHome: "Back to home",
      },
      errors: {
        emptyCartTitle: "Empty cart",
        emptyCartMessage: "Add products before continuing.",
        missingFields: "Please complete all required fields.",
        missingAddress: "Please provide a shipping address.",
        missingCashAmount: "Tell us how much you'll pay with (numbers only).",
        cashTooLow: "The cash amount cannot be lower than the total.",
        generic: "An error occurred while processing the purchase.",
      },
    },
    auth: {
      login: {
        secureBadge: "Secure login",
        title: "Log in",
        emailLabel: "Email",
        emailPlaceholder: "you@email.com",
        passwordLabel: "Password",
        passwordPlaceholder: "••••••••",
        showPassword: "Show password",
        hidePassword: "Hide password",
        recoverHint: "Can’t get in? Try recovering your password.",
        recoverLink: "Recover password",
        loading: "Logging in...",
        loadingButton: "Logging in...",
        submit: "Log in",
        noAccount: "Don't have an account?",
        signupLink: "Sign up",
        toastSuccessTitle: "Signed in",
        toastSuccessMessage: "Welcome back {email}",
        toastErrorTitle: "Login error",
        toastErrorMessage: "Incorrect email or password",
      },
      signup: {
        badge: "Create account",
        title: "Create account",
        subtitle: "Sign up to track your purchases at Abul Cell.",
        nameLabel: "Name",
        namePlaceholder: "Your name",
        emailLabel: "Email",
        emailPlaceholder: "you@email.com",
        passwordLabel: "Password",
        passwordPlaceholder: "Minimum 8 characters",
        repeatPasswordLabel: "Repeat password",
        repeatPasswordPlaceholder: "Repeat your password",
        showPassword: "Show password",
        hidePassword: "Hide password",
        loading: "Creating account...",
        loadingButton: "Signing up...",
        submit: "Sign up",
        haveAccount: "Already have an account?",
        loginLink: "Log in",
        successTitle: "Account created",
        successMessage: "Your account was created successfully. You can now log in.",
        errorTitle: "Sign up error",
        errorMessage: "We couldn't create the account",
        passwordMismatchTitle: "Passwords don't match",
        passwordMismatchMessage: "Passwords do not match",
      },
      forgotPassword: {
        title: "Reset password",
        subtitle: "We'll send you a link so you can create a new password.",
        emailLabel: "Email",
        emailPlaceholder: "you@email.com",
        submit: "Send link",
        sending: "Sending...",
        backToLogin: "Back to login",
        successTitle: "All set.",
        successMessage: "If the email exists, you'll receive a recovery link shortly.",
        errors: {
          missingEmail: "Enter your email.",
          generic: "We couldn't process your request.",
        },
      },
      resetPassword: {
        title: "New password",
        subtitle: "Enter your new password and confirm it.",
        passwordLabel: "New password",
        passwordPlaceholder: "Minimum 8 characters",
        confirmPasswordLabel: "Repeat password",
        confirmPasswordPlaceholder: "Repeat your password",
        showPassword: "Show password",
        hidePassword: "Hide password",
        saving: "Saving...",
        submit: "Change password",
        backToLogin: "Back to login",
        requestLink: "Request link again",
        successTitle: "Password updated.",
        successMessage: "Redirecting you to login…",
        errors: {
          missingToken: "Invalid or missing token. Request the link again.",
          missingTokenInline: "Missing token. Request the recovery link again.",
          shortPassword: "Password must be at least 8 characters.",
          passwordMismatch: "Passwords do not match.",
          generic: "We couldn't change the password.",
        },
      },
      verifyEmail: {
        title: "Verify your email",
        subtitle: "We sent a code to",
        codeLabel: "Code (6 digits)",
        codePlaceholder: "123456",
        confirm: "Confirm",
        verifying: "Verifying...",
        resend: "Resend code",
        resendSuccess: "All set ✅ We sent a new code.",
        later: "Verify later",
        hint: "You can verify it later from",
        profileLink: "My profile",
        errors: {
          shortCode: "Enter the 6-digit code.",
          invalidCode: "Invalid code.",
          resendFailed: "We couldn't resend the code.",
        },
      },
    },
    profile: {
      title: "My profile",
      subtitle: "Manage your account details.",
      loginRequired: "You need to log in to view your profile.",
      goToLogin: "Go to login",
      theme: {
        title: "Theme",
        description: "Choose how the app looks for you.",
        toggle: "Toggle theme",
        light: "Light mode",
        dark: "Dark mode",
      },
      labels: {
        name: "Name",
        email: "Email",
        verification: "Verification",
      },
      verified: "Verified",
      pending: "Pending",
      verify: {
        title: "Your email is not verified yet.",
        subtitle: "Check your inbox. If it didn't arrive, you can resend it.",
        success: "Done ✅ We resent the code. Check your email.",
        error: "We couldn't resend the code.",
        loading: "Resending...",
        resend: "Resend verification",
        enterCode: "Enter code now",
      },
      addresses: {
        title: "My addresses",
        loading: "Loading addresses...",
        empty: "You don't have saved addresses.",
        default: "Default",
        postalCode: "ZIP:",
        apartment: "Apt",
        floor: "Floor",
        bell: "Doorbell",
        makeDefault: "Set as default",
        edit: "Edit",
        delete: "Delete",
        cancelEdit: "Cancel edit",
        types: {
          house: "House",
          apartment: "Apt",
          office: "Office",
        },
      },
      addressErrors: {
        load: "We couldn't load the addresses",
        delete: "We couldn't delete the address",
        setDefault: "We couldn't set it as default.",
      },
      addressForm: {
        title: "Add address",
        labelPlaceholder: "Home, Work...",
        streetPlaceholder: "Street and number",
        cityPlaceholder: "City",
        provincePlaceholder: "State / Province",
        postalCodePlaceholder: "ZIP / Postal code",
        typeLabel: "Type",
        types: {
          house: "House",
          apartment: "Apartment",
          office: "Office",
          other: "Other",
        },
        apartmentLabel: "Apartment (optional)",
        apartmentPlaceholder: "A, 2B, etc.",
        floorLabel: "Floor (optional)",
        floorPlaceholder: "3",
        bellLabel: "Doorbell (optional)",
        bellPlaceholder: "Moreno / 3B",
        notesLabel: "Delivery notes (optional)",
        notesPlaceholder: "Between streets..., black gate, etc.",
        setDefault: "Use as default",
        submit: "Save address",
      },
    },
    contact: {
      badge: "Contact",
      title: "Contact us",
      subtitle: "Questions about a product or need a quote? Send us a message.",
      sending: "Sending message...",
      toastSuccessTitle: "Message sent",
      toastSuccessMessage: "Thanks! We'll get back to you shortly.",
      toastErrorTitle: "Couldn't send message",
      toastErrorMessage: "Something went wrong while sending your message. Please try again.",
      form: {
        nameLabel: "Name",
        emailLabel: "Email",
        subjectLabel: "Subject",
        messageLabel: "Message",
        attachmentsLabel: "Attachments (receipt / photos)",
        attachmentsHint: "Images or PDF. Max 8MB total.",
        sending: "Sending...",
        submit: "Send message",
      },
      storeDetailsTitle: "Store details",
      storeAddressLabel: "Address:",
      storeAddressValue: "(store address goes here)",
      storeHoursLabel: "Hours:",
      storeHoursValue: "Monday to Friday, 10am to 7pm.",
      storeEmailLabel: "Email:",
      storePhoneLabel: "Phone:",
    },
    offers: {
      badge: "Deals",
      title: "Deals",
      subtitle: "Products with special discounts at Abul Cell.",
      states: {
        loadingTitle: "Loading deals…",
        loadingSubtitle: "Finding the best picks for you.",
        errorTitle: "We couldn't load the deals",
        errorSubtitle: "Try again in a moment.",
        emptyTitle: "There are no active deals right now",
        emptySubtitle: "Check back later, there are always new offers.",
      },
    },
    store: {
      badge: "Store",
      title: "Store",
      subtitle: "Browse all products from Abul Cell.",
      categories: {
        phones: "Phones",
        laptops: "Laptops",
        peripherals: "Peripherals",
        audio: "Audio",
        gaming: "Gaming",
        accessories: "Accessories",
      },
      actions: {
        loading: "Loading...",
        refresh: "Refresh",
        clear: "Clear",
        retry: "Retry",
        clearFilters: "Clear filters",
      },
      filters: {
        searchLabel: "Search",
        searchPlaceholder: "Search by name or description...",
        clearSearch: "Clear search",
        categoryLabel: "Category",
        allCategories: "All categories",
        sortLabel: "Sort",
        sort: {
          relevance: "Relevance",
          priceAsc: "Price: low to high",
          priceDesc: "Price: high to low",
          nameAsc: "Name: A-Z",
        },
        resultsLabel: "Results",
        resultsPlaceholder: "—",
      },
      states: {
        loadingTitle: "Loading products…",
        loadingSubtitle: "Hang tight, the catalog is loading.",
        errorTitle: "Something went wrong while loading products",
        errorSubtitle: "Try again. If it persists, we'll check the endpoint.",
        emptyTitle: "We couldn't find products with those filters",
        emptySubtitle: "Try changing the category or clearing the search.",
      },
    },
    productCard: {
      offer: "Deal",
      outOfStock: "Out of stock",
      noImage: "No image",
      stock: {
        ok: "Stock: {stock}",
        low: "Only {stock} left",
      },
      removeOne: "Remove one",
      maxStock: "Maximum stock reached",
      addToCart: "Add to cart",
      added: "Added",
      add: "Add",
    },
    admin: {
      title: "Admin dashboard",
      subtitle: "Hi, {name}. Manage Abul Cell.",
      accessDenied: {
        title: "Access denied",
        subtitle: "You don't have permission to view this section.",
        back: "Back",
      },
      errors: {
        loadProducts: "We couldn't load the products.",
        loadOrders: "We couldn't load the orders.",
        loadUsers: "We couldn't load the users.",
        saveProduct: "We couldn't save the product.",
        deleteProduct: "We couldn't delete the product.",
        updateOrderStatus: "We couldn't update the status.",
      },
      notifications: {
        productUpdated: "Product updated.",
        productCreated: "Product created.",
        productDeleted: "Product deleted.",
        orderUpdated: "Order status updated.",
      },
      headerSubtitle: {
        products: "{count} products",
        payments: "{count} orders",
        users: "User management",
        profits: "Revenue from paid orders",
      },
      kpis: {
        products: "{count} products",
        catalog: "Catalog management",
        orders: "{count} orders",
        payments: "Payments and statuses",
        users: "{count} users",
        today: "Today: ${amount}",
        week: "Week: ${amount}",
        month: "Month: ${amount}",
        year: "Year: ${amount}",
      },
      pagination: {
        showing: "Showing {start} – {end} of {total}",
        prev: "Previous",
        next: "Next",
      },
      payments: {
        title: "Payments / Orders",
        loading: "Loading orders...",
        empty: "There are no orders yet.",
        headers: {
          customer: "Customer",
          method: "Method",
          date: "Date",
          status: "Status",
          total: "Total",
        },
        status: {
          pending: "Pending",
          paid: "Paid",
          cancelled: "Cancelled",
        },
      },
      users: {
        title: "Users",
        loading: "Loading...",
        loadingList: "Loading users...",
        refresh: "Refresh",
        empty: "No users to display.",
        headers: {
          id: "ID",
          name: "Name",
          email: "Email",
          role: "Role",
        },
        roles: {
          admin: "Admin",
          user: "User",
        },
      },
      products: {
        form: {
          editTitle: "Edit product",
          newTitle: "New product",
          idLabel: "ID {id}",
          editDescription: "Update the product details and save the changes.",
          newDescription: "Fill in the details to add a product to the store.",
          name: "Name",
          slug: "Slug (unique identifier)",
          price: "Price (ARS)",
          stock: "Stock",
          stockPlaceholder: "0",
          category: "Category",
          categoryPlaceholder: "Phones, Laptops, Accessories...",
          imageFile: "Product image",
          imageFileHint: "Upload an image from your computer (JPG/PNG/WebP).",
          imageUrl: "Image URL (optional)",
          imageUrlPlaceholder: "https://... (optional)",
          description: "Description",
          isOffer: "Mark as offer",
          offerLabel: "Offer label",
          offerPlaceholder: "10% OFF, DEAL, etc.",
          saving: "Saving...",
          save: "Save changes",
          create: "Create product",
          cancel: "Cancel",
        },
        summary: {
          total: "Total",
          offers: "Offers",
          lowStock: "Low stock",
        },
        list: {
          title: "Current products",
          loading: "Loading products...",
          empty: "There are no products yet.",
          headers: {
            name: "Name",
            category: "Category",
            price: "Price",
            stock: "Stock",
            offer: "Offer",
            actions: "Actions",
          },
          offer: "Offer",
          uncategorized: "Uncategorized",
        },
      },
      profits: {
        title: "Revenue",
        kpis: {
          today: "Today",
          week: "Week",
          month: "Month",
          year: "Year",
        },
        chartTitle: {
          week: "Last 7 days",
          month: "Last 12 months",
          year: "Last 5 years",
        },
        chartSubtitle: "Revenue by period",
        range: {
          week: "Week",
          month: "Month",
          year: "Year",
        },
      },
      confirm: {
        title: "Confirm deletion",
        subtitle: "You are about to delete {name}. This action cannot be undone.",
        fallbackItem: "this product",
        close: "Close",
        cancel: "Cancel",
        deleting: "Deleting...",
        confirm: "Yes, delete",
      },
      sidebar: {
        title: "Navigation",
        products: "Products",
        payments: "Payments",
        users: "Users",
        profits: "Revenue",
      },
    },
    checkoutStatus: {
      success: {
        badge: "Payment received",
        title: "Payment successful",
        subtitle: "Thanks for your purchase! You'll receive an email with the details shortly.",
        steps: {
          email: {
            title: "Email confirmation",
            subtitle: "You'll receive the order details and payment status.",
          },
          prep: {
            title: "Order preparation",
            subtitle: "We prepare your order and coordinate shipping or pickup.",
          },
        },
        actions: {
          home: "Back to home",
          store: "Continue shopping",
        },
      },
      failure: {
        badge: "Payment not completed",
        title: "Payment not completed",
        subtitle:
          "Your payment could not be completed. Don't worry: the purchase isn't confirmed until payment clears.",
        tips: {
          balance: "Check your balance or available limit.",
          method: "Try another card or method in Mercado Pago.",
          retry: "If the flow got stuck, go back to the cart and retry.",
        },
        actions: {
          retry: "Retry payment",
          cart: "Back to cart",
          store: "Go to store",
        },
      },
    },
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    () => localStorage.getItem("language") || "es"
  );

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const value = useMemo(() => {
    function t(key, params = {}) {
      const parts = key.split(".");
      let current = TRANSLATIONS[language];
      for (const p of parts) {
        if (!current || typeof current !== "object") return key;
        current = current[p];
      }
      if (current == null) return key;
      if (typeof current === "string" && params && Object.keys(params).length > 0) {
        return current.replace(/\{(\w+)\}/g, (match, k) =>
          Object.prototype.hasOwnProperty.call(params, k) ? params[k] : match
        );
      }
      return current;
    }

    return {
      language,
      setLanguage,
      t,
    };
  }, [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error("useLanguage debe usarse dentro de LanguageProvider");
  }
  return ctx;
}